### ISSUE TITLE
Failure in Java 11

### ISSUE THREAD

**Issue by blakemcbride** [dvare/dynamic-loader#4]
The following code works fine in Java 8 but fails in Java 11.0.7:

            DynamicCompiler dc = new DynamicCompiler();
            dc.addSource(cname, code);
            Map<String, Class<?>> compiled = dc.build();
            jclass = compiled.get(cname);

In Java 8, "compiled" is length 1 and "class" is a valid object.  In Java 11, "compiled" is length 0 and "jclass" is null.  All of the code is the same in both scenarios.

I am using Dynamic Loader 3.0.

**Comment by hammadirshad** [comment]
Hi, @blakemcbride
for java 9+ you need to export java modules that your code is using.
https://github.com/dvare/dynamic-loader/wiki#java-module-support-from-version-30
please provide sample code string for details

**Comment by blakemcbride** [comment]
I added:
    `dc.addOption("--add-exports", "java.sql/java.sql=ALL-UNNAMED");`

I am getting:

```
org.dvare.dynamic.exceptions.DynamicCompilerException: Compilation Error
line: 14 , message: cannot access java.util.Map
  class file for java.util.Map not found , 

        at org.dvare.dynamic.compiler.DynamicCompiler.build(DynamicCompiler.java:192)
        at org.kissweb.rest.JavaService.loadJavaClass(JavaService.java:143)
        at org.kissweb.rest.JavaService.tryJava(JavaService.java:51)
        at org.kissweb.rest.ProcessServlet.run2(ProcessServlet.java:266)
        at org.kissweb.rest.ProcessServlet.run(ProcessServlet.java:49)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:834)
```

I will try to reduce the problem.  Thanks!

**Comment by blakemcbride** [comment]
I simplified the issue to its simplest.  It is attached herewith.  See README.txt
[Test-01.tar.gz](https://github.com/dvare/dynamic-loader/files/4641653/Test-01.tar.gz)

**Comment by hammadirshad** [comment]
As descibe in message ` message: cannot access java.util.Map` try to export  java.base/java.util package 
` dynamicCompiler.addOption("--add-exports", "java.base/java.util=ALL-UNNAMED");`

**Comment by blakemcbride** [comment]
I tried that, as shown in the test program I sent.  It didn't solve the problem.  Thanks.

**Comment by blakemcbride** [comment]
I was using a different line than the one you just gave me.  Your line works!  Thank you!
